### ISSUE TITLE
Graph missing current time highlight

### ISSUE THREAD

**Issue by Zardocius** [thevaldev/epossu-fi#23]
There is no highlight for current hour in graph while it was before, please fix! :)

![image](https://github.com/user-attachments/assets/dfc031fd-a630-4355-ac1b-b9d025d9dcc2)

**Comment by thevaldev** [comment]
This issue was caused by the "daylight saving" time to end which returns 2 of the 3am prices making the graph get confused.
I've implemented a back-end change to fix this issue.
